name: county-drupal
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: 9cab3740-4631-4529-a4de-d6ef75472d78
  ah_site_group: wcor
  build:
    run_scripts: true
  cache: true
  composer_version: '2.1.5'
  inbox: false
  php: '8.0'
  xdebug: false
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://county-drupal.lndo.site"
    type: php:8.0
    build_as_root:
      - mkdir -p /mnt/gfs/wcor.LANDO/nobackup
      - mkdir -p /mnt/files/wcor.LANDO/sites/default/files-private
      - chown -R www-data:www-data /mnt/gfs
      - chown -R www-data:www-data /mnt/files/wcor.LANDO/sites/default
      - chmod -R g+rw /mnt/gfs
      - chmod -R g+rw /mnt/files/wcor.LANDO/sites/default
