shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: ''
    pass: ''
allow_cli: true
debug_header: false
print: 'Env: Develop'
method: 0
paths: ''
allowlist: ''
http_method_allowlist: {  }
domains: ''
whitelist: ''
