_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'County Employees'
login_link_show: true
user_name: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'
unique_id: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'
mail_attr: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'
header_no_cache: false
role:
  population: ''
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    authenticated: authenticated
    administrator: administrator
  default_login_users: '1'
logout_goto_url: ''
user_register_original: admin_only
sync:
  mail: true
  user_name: true
autoenablesaml: true
debug: false
secure: false
httponly: false
