seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: true
      webkit: false
    report-only: true
    default-src: '''self'' *.washcoor.us *.ahdev.cloud *.acquia-sites.com'
    script-src: '''self'' *.pagespeed-mod.com *.google-analytics.com'
    object-src: ''
    img-src: '''self'' *.google-analytics.com data:'
    media-src: ''
    frame-src: ''
    frame-ancestors: ''
    child-src: ''
    font-src: '''unsafe-inline''  fonts.gstatic.com'
    connect-src: ''
    report-uri: /report-csp-violation
    upgrade-req: true
    policy-uri: ''
    style-src: '''unsafe-inline'' *.googleapis.com *.washcoor.us *.ahdev.cloud *.acquia-sites.com'
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 2
seckit_csrf:
  origin: false
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '3'
  x_frame_allow_from: 'https://translate.googleusercontent.com'
seckit_ssl:
  hsts: true
  hsts_subdomains: true
  hsts_max_age: 31536000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: no-referrer-when-downgrade
  disable_autocomplete: true
_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
